server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/edusystem?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: wh20040108
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.example.newDemo.pojo
  mybatis:
    mapper-locations=classpath:mybatis/mapper:


