server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart_home?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: wh20040108
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    cache: false
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true



